### ISSUE TITLE
Economy

### ISSUE THREAD

**Issue by b3r3nd** [b3r3nd/berendbotje#26]
Economy system with mini games.

From richard:

"A economic system where you can get coins (maybe an alternative name) by levelling for example. You could spend the coins (by the kind of same way like it works on twitch) on in server items like roles, access to channels, steam keys etc."

**Comment by Riensjard** [comment]
Minigames e.g. 
 - Gambling on certain things like maybe a football match. So a mod/admin or someone with a role to create these things can make a gamble thing so if certain people win you can double your coins with a max amount of money you can bet on these activities? (To prevent people with like 1 million coins to make it 2 million since this could be unbalanced). 
 - Ofcourse the normal gambling like the blackjack or maybe roulette.
 - Implement the commands for economy we already have like /work or /beg
